### ISSUE TITLE
Other deployment options?

### ISSUE THREAD

**Issue by kwri-avongluck** [CiscoSecurity/tr-05-serverless-alienvault-otx#12]
Why do all of these require AWS lambda?  Any container or gcp deployment options?

**Comment by maugertg** [comment]
We chose to use AWS Serverless for multiple reasons (some specific to AWS others Serverless in general):

1. Threat Response is hosted in AWS, this reduces latency by putting the Serverless Relay as close to Threat Response as possible
2. AWS Serverless has the most adoption, which means there are more supporting libraries such as [Zappa ](https://github.com/Miserlou/Zappa)
3. Simplifies deployment, once environment is configured new Serverless Relays can be can be deployed in ~1 minute with 3 steps
4. Reduces management overhead (there are no servers to keep up to date)
5. Reduces cost to negligible amounts annually (high estimates of $50 or less annually for 7 modules deployed) 

As part of the design, [Zappa ](https://github.com/Miserlou/Zappa) was chosen because it enables easy deployment of Python Flask apps. Each of the Serverless Relays is a simple Flask app, this provides for extremely easy development and testing. Executing `flask run` inside the Serverless Relay directory will run an instance locally on port 5000. This also makes it very easy to host multiple Serverless Relays on a server as WSGI applicatoins with either Nginx or Apache. Digital ocean has a tutorial [here](https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-20-04) that uses Gunicorn and Nginx. I know of three individuals who have taken this approach instead of using AWS.

There are currently no plans to create container or GCP deployment packages. Since each Serverless Relay is a Flask app, it shouldn't be very difficult to build a container. Digital Ocean has a great tutorial for doing that [here](https://www.digitalocean.com/community/tutorials/how-to-build-and-deploy-a-flask-application-using-docker-on-ubuntu-18-04).

I have not found any packages similar to Zappa for GCP that will deploy and connect all of the functions together in GCP using Cloud Functions. Since the Serverless Relays are Flask apps, I suspect someone who is familiar with GCP could get everything running within an afternoon.
